create table test  (_id INTEGER DEFAULT '0' NOT NULL PRIMARY KEY AUTOINCREMENT, myval VARCHAR(25) NOT NULL);
create table test2 (_id INTEGER DEFAULT '0' NOT NULL PRIMARY KEY AUTOINCREMENT, myval VARCHAR(25) NOT NULL);
